### PR TITLE
V5

### PR DESCRIPTION
**Pull request by cwdcwd**

### CODE REVIEW

**Comment by sachin-maheshwari** [comment]
@cwdcwd  as checked by deploying this branch (v5) on "dev"..getting error - https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logEventViewer:group=/aws/ecs/tc-bus-api;stream=tc-bus-api_DEV/tc-bus-api-container/1b7f4894-aab8-4dba-9f36-8bbbc92c5f62
screen shot 2018-06-26 at 6 00 31 pm

**Comment by cwdcwd** [comment]
@sachin-maheshwari would it be that we need to config some env vars? I see `Swagger-ui is available on http://localhost:3000/docs` before that error line which seems wrong

**Comment by sachin-maheshwari** [comment]
@cwdcwd yes, if you are setting-up locally, you need some env vars. You can refer dev for same - https://console.aws.amazon.com/ecs/home?region=us-east-1#/taskDefinitions/tc-bus-api-task/82

**Comment by sachin-maheshwari** [comment]
@cwdcwd Looks like my testing "timestamp" was wrong. I am trying to deploy on Dev and check again.

**Comment by sachin-maheshwari** [comment]
@cwdcwd its working fine. There was validation issue. Further I'll verify more once we fix the old format bus payload changes in down stream services i.e. tc-project and tc-message.

**Comment by cwdcwd** [comment]
thanks @sachin-maheshwari !

**Comment by callmekatootie** [comment]
@cwdcwd Added auth checks

**Pull request merged**
